workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    integrations:
      app_store_connect: Metaprime
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.servicios4j.deudasql
      vars:
        APP_STORE_APPLE_ID: 6SU796DHY2
      flutter: stable
    scripts:
      - name: Set up code signing settings on Xcode project
        script: | 
          xcode-project use-profiles
      - name: Get Flutter packages
        script: | 
          flutter packages pub get
      - name: Install pods
        script: | 
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter analyze
        script: | 
          flutter analyze
      - name: Flutter unit tests
        script: | 
          flutter test
        ignore_failure: true
      - name: Flutter build ipa
        script: | 
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist
        #    --build-name=1.0.0 \
        #    --build-number=$(($(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID") + 1)) \
        #    --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - pablo.lagues@gmail.com
        notify:
          success: true
          failure: false
      app_store_connect:
        auth: integration

        # Configuration related to TestFlight (optional)
        # Note: This action is performed during post-processing.
        submit_to_testflight: true
        beta_groups: # Specify the names of beta tester groups that will get access to the build once it has passed beta review.
          - group name 1
          - group name 2

        # Configuration related to App Store (optional)
        # Note: This action is performed during post-processing.
        submit_to_app_store: false
      
      #Firebase Integration
      firebase:
        # use this line to authenticate via service account
        firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
        
        # or this line to authenticate via token:
        # firebase_token: $FIREBASE_TOKEN

        ios:
          # Add your iOS app id retrieved from Firebase console
          app_id: 1:294273894817:ios:83331af043781e66fc23e0
          
          # Add one or more groups that you wish to distribute your iOS application to.
          # You can create groups in the Firebase console
          groups:
            - firebase_credentials